/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetrosRouteImport } from './routes/retros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetroIndexRouteImport } from './routes/retro/index'
import { Route as TeamTeamIdRouteImport } from './routes/team/$teamId'
import { Route as RetroRetroIdRouteImport } from './routes/retro/$retroId'

const RetrosRoute = RetrosRouteImport.update({
  id: '/retros',
  path: '/retros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetroIndexRoute = RetroIndexRouteImport.update({
  id: '/retro/',
  path: '/retro/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const RetroRetroIdRoute = RetroRetroIdRouteImport.update({
  id: '/retro/$retroId',
  path: '/retro/$retroId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/retros': typeof RetrosRoute
  '/retro/$retroId': typeof RetroRetroIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/retro/': typeof RetroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/retros': typeof RetrosRoute
  '/retro/$retroId': typeof RetroRetroIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/retro': typeof RetroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/retros': typeof RetrosRoute
  '/retro/$retroId': typeof RetroRetroIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/retro/': typeof RetroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/retros'
    | '/retro/$retroId'
    | '/team/$teamId'
    | '/retro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/retros'
    | '/retro/$retroId'
    | '/team/$teamId'
    | '/retro'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/retros'
    | '/retro/$retroId'
    | '/team/$teamId'
    | '/retro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RetrosRoute: typeof RetrosRoute
  RetroRetroIdRoute: typeof RetroRetroIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
  RetroIndexRoute: typeof RetroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retros': {
      id: '/retros'
      path: '/retros'
      fullPath: '/retros'
      preLoaderRoute: typeof RetrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retro/': {
      id: '/retro/'
      path: '/retro'
      fullPath: '/retro/'
      preLoaderRoute: typeof RetroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retro/$retroId': {
      id: '/retro/$retroId'
      path: '/retro/$retroId'
      fullPath: '/retro/$retroId'
      preLoaderRoute: typeof RetroRetroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RetrosRoute: RetrosRoute,
  RetroRetroIdRoute: RetroRetroIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
  RetroIndexRoute: RetroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
